flatpak/xdg-desktop-portal-gtk

org.freedesktop.impl.portal.desktop.gtk.service.in

It was still using 'flatpak-gtk', from the old repository

Point to the right binary of the portal implementation in the service file

---

appchooser.c
appchooserdialog.c
appchooserdialog.h

This addresses issue https://github.com/flatpak/xdg-desktop-portal/issues/10

Consider the 'use-default' option if present, to avoid using a GtkDialog

---

COPYING
appchooser.c
appchooser.h
appchooserdialog.c
appchooserdialog.h
appchooserrow.c
appchooserrow.h
filechooser.c
filechooser.h
print.c
print.h
xdg-desktop-portal-gtk.c
xdg-desktop-portal-gtk.h

Considering this project relates to flatpak, one could assume that the license for this source code is LGPL 2+, but that would be just an assumption, so I think it would be great if we could specify this explicitly, so that people willing to ship this code knows what to use.

Specify a software license

---

appchooserdialog.ui
appchooserrow.ui
screenshotdialog.ui

These contain translatable strings, but they won't be translated
at runtime unless we tell GtkBuilder about the domain.

Set gettext domain in ui files

---

src/filechooser.c

We no longer have separate OpenFile and OpenFiles methods;
instead there is a 'multiple' option.

Simplify filechooser portal api

---

src/access.c

src/access.c:288:3: error: format not a string literal and no format arguments [-Werror=format-security]
gtk_message_dialog_format_secondary_text (GTK_MESSAGE_DIALOG (dialog), arg_subtitle);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix string literal format warning

---

src/Makefile.am.inc

When building outside of the srcdir, we need to tweak the inclusion paths.
This fixes the build for `builddir != srcdir` environments, like GNOME Continuous.

build: Add appropriate inclusion paths

---

configure.ac
src/access.c
src/accountdialog.h
src/appchooserdialog.c
src/appchooserdialog.h
src/appchooserrow.h
src/externalwindow-wayland.c
src/externalwindow-wayland.h
src/externalwindow-x11.c
src/externalwindow-x11.h
src/externalwindow.h
src/print.c
src/screenshotdialog.h

Depend on at least version 3.16 for gtk_label_set_xalign(). This version
of GTK+ also depends on GLib 2.44, which is the minimum needed for
g_autoptr().

configure: Update GTK+ dependency

---

configure.ac
data/Makefile.am.inc
data/org.freedesktop.impl.portal.desktop.gtk.service.in
data/xdg-desktop-portal-gtk.service.in

This puts xdg-desktop-portal-gtk in its own cgroup where systemd can
apply resource limits, etc. if configured to do so, and avoids
inheriting any non-standard execution environment that dbus-daemon
might have.

Add a systemd user unit corresponding to the session service

---

po/Makevars

Current encoding is latin-1. As all po files are UTF-8, I suggest to also use the UTF-8 encoding for Makevars.

Encode po/Makevars in UTF-8

---

data/Makefile.am.inc
data/xdg-desktop-portal-gtk.desktop.in.in
po/POTFILES.in
src/xdg-desktop-portal-gtk.c

This lets us associate a name and icon with the name
xdg-desktop-portal-gtk, for the cases where we fail to
make the portal dialog transient for an application toplevel
window.

Install a desktop file

---

src/appchooserdialog.c

load_from_path() doesn't support resource:// URIs, so we're currently
trying to load a very weirdly named file from the filesystem ...

appchooserdialog: Fix CSS loading

---

data/xdg-desktop-portal-gtk.desktop.in.in

Add a comment above the msgid, so the translator knows that it is an icon name

.desktop: Tell translators to not translate icon name

---

src/notification.c

When handling incoming method calls via the generated ::handle-*
signals, handlers are expected to return %TRUE to indicate that
the invocation has been handled. In the case that no handler handles
the invocation, the method is considered unknown and a corresponding
D-Bus error is returned.
As we currently connect handlers with no return value at all, we end
up with a Schroedinger method that may or may not exist - as the gtk
code path calls methods that do return %TRUE, there's a good chance
that we are lucky and something true-ish is picked from the stack,
but for the fdo path all bets are off.
Fix this by moving the return values to the actual signal handlers.

notification: Fix ::handle-* return values

---

src/notification.c

See patches.
I'm including the last one for completeness, but maybe we should leave it out so the unloved option can die a slow death ...

Fix notification icons in the fdo code path

---

src/Makefile.am.inc

It is generated by `make`. I previously tried to exclude this from
tarballs in commit 9e92b02, but it is used in a test program as well
as in the portal implementation itself.

Clean up src/resources.c, and don't distribute in tarballs

---

src/email.c

If we fail to launch an email client, we should return
2 (error), not 1 (canceled). This lets us fall back to
trying other things on the caller side.

email: return the correct response

---

src/externalwindow.c

Spotted by Coverity, CID 207681.
Signed-off-by: Philip Withnall <withnall@endlessm.com>

externalwindow: Add a missing break in a switch statement

---

src/filechooser.c

Opening a file chooser is currently emitting:
> GLib-CRITICAL **: '&ay' is not a valid GVariant format string
This fixes that.
* src/filechooser.c (handle_open): Correct the GVariant format for
bytestrings.

Fix a GLib critical warning when opening a file chooser.

---

src/Makefile.am.inc
src/screenshot.c
src/screenshotdialog.c
src/screenshotdialog.css
src/screenshotdialog.h
src/screenshotdialog.ui
src/xdg-desktop-portal-gtk.gresource.xml

Similar to gnome-screenshot --interactive, expose options
for window and area screenshots.

Add options to the screenshot portal

---

data/Makefile.am.inc
data/gtk.portal
data/org.gnome.Mutter.DisplayConfig.xml
data/org.gnome.Mutter.RemoteDesktop.xml
data/org.gnome.Mutter.ScreenCast.xml
po/POTFILES.in
src/Makefile.am.inc
src/displaystatetracker.c
src/displaystatetracker.h
src/gnomescreencast.c
src/gnomescreencast.h
src/remotedesktop.c
src/remotedesktop.h
src/remotedesktopdialog.c
src/remotedesktopdialog.h
src/remotedesktopdialog.ui
src/screencast.c
src/screencast.h
src/screencastdialog.c
src/screencastdialog.h
src/screencastdialog.ui
src/screencastwidget.c
src/screencastwidget.h
src/screencastwidget.ui
src/session.c
src/session.h
src/xdg-desktop-portal-gtk.c
src/xdg-desktop-portal-gtk.gresource.xml

Uses unreleased version of org.gnome.Mutter.ScreenCast and org.gnome.Mutter.RemoteDesktop. I'll post a link to the mutter branch when it's ready for consumption.

Screen cast and remote desktop portal backends

---

src/gtkbackports.c

The app can send us nonsense. Lets not crash if there is no
paper size.
Should fix https://github.com/flatpak/xdg-desktop-portal-gtk/issues/128.

print portal: Avoid a crash

---

data/org.gnome.Shell.Screenshot.xml
src/screenshot.c

This will be used to implement a color picker for
sandboxed apps. The implementation here uses a
new gnome-shell D-Bus API.

screenshot: Add a PickColor method

---

configure.ac

Older versions don't have the new colour picker API.
Signed-off-by: Simon McVittie <smcv@collabora.com>

build: Require xdg-desktop-portal 1.0

---

src/appchooser.c
src/appchooser.h
src/filechooser.c
src/filechooser.h
src/print.c
src/print.h
src/xdg-desktop-portal-gtk.c

Use the GNOME lockdown settings for printing, file saving
and application handlers to set the new 'disabled' properties
on the corresponding portal backends.

Respect lockdown settings

---

src/appchooser.c
src/appchooserdialog.c
src/appchooserdialog.h

Implement this new method that lets the frontend update
the app chooser dialog when new apps appear. This is
for example happening when the user uses the link to
go from the appchooser dialog to GNOME Software to install
a new app.
Closes: #144

appchooser: Implement UpdateChoices

---

src/accountdialog.c
src/appchooserdialog.c
src/remotedesktopdialog.c
src/screencastdialog.c
src/screenshotdialog.c

Dialog window closing should be handled as if the user cancelled the
operation. Add delete-event handlers to signal cancellation and hide the
dialog.

Handle dialog windows being closed

---

src/email.c

It is possible that there is no default mailto handler.
Don't crash in that case.

email: Be more careful when selecting a handler

---

src/xdg-desktop-portal-gtk.c

I didn't mean to format every message like an error.

Fix an oversight in message handling

---

src/filechooser.c

Make the "Open files read-only" string translatable. Just a quick, untested fix, but it should work fine.

Fix translatable string

---

src/gnomescreencast.c

With 3.32, the `org.gnome.Mutter.ScreenCast` API version will be bumped to 2. Lets not make that fail the portal backend. No functional changes are needed to continue to work as is.
This should probably be backported to stable branches that wants to support running alongside GNOME 3.32.

Bump GNOME screen cast API version

---

src/gnomescreencast.c
src/gnomescreencast.h
src/remotedesktop.c
src/remotedesktop.h
src/remotedesktopdialog.c
src/remotedesktopdialog.h
src/screencast.c
src/screencast.h
src/screencastdialog.c
src/screencastdialog.h
src/screencastwidget.c
src/screencastwidget.h

To let the API user select between embedding, hiding or sending cursor data as pipewire metadata.

Screen cast cursor mode

---

src/lockdown.c

The property was renamed to disable-sound-output. Follow along.

lockdown: Use the right property name

---

data/gtk.portal
src/Makefile.am.inc
src/background.c
src/background.h
src/fdonotification.c
src/fdonotification.h
src/notification.c
src/xdg-desktop-portal-gtk.c

This is an implementation of the platform-dependent parts of https://github.com/flatpak/xdg-desktop-portal/pull/319

Background monitor

---

src/appchooserdialog.ui

Give the "image-button" class to the "more" buttons to make them have a
1:1 aspect ratio, hence making them circles and not pill-shaped.
Before:
After:

appchooserdialog: Make the "more" buttons circles

---

src/screencast.c

If the ScreenCast API has an unsupported version we return FALSE from `start_session` but without setting the `error` parameter. This then segfaults when we try to print the failure message here:
```c
if (!start_session (dialog_handle->session, selections, &error))
{
g_warning ("Failed to start session: %s", error->message);
response = 2;
}
```
Also added the actual and supported API versions to the error message.

Fix crash with unsupported ScreenCast API version

---

src/Makefile.am.inc
src/gnomescreencast.c
src/remotedesktopdialog.c
src/screencast.c
src/screencastdialog.c
src/screencastdialog.ui
src/screencastwidget.c
src/screencastwidget.h
src/screencastwidget.ui
src/shellintrospect.c
src/shellintrospect.h

This is a continuation of https://github.com/flatpak/xdg-desktop-portal-gtk/pull/217 which adds asynchronous window list retrieval and a couple of minor alterations.

Add window screen cast #2

---

configure.ac
data/gtk.portal
src/Makefile.am.inc
src/fc-monitor.c
src/fc-monitor.h
src/gsd-remote-display-manager.c
src/gsd-remote-display-manager.h
src/settings.c
src/settings.h
src/xdg-desktop-portal-gtk.c

This copies the settings code from xdg-desktop-portal to create a settings backend,
and then
applies the same logic that gnome-settings-daemon
uses to override the enable-animations setting.

settings: disable animations when remote

---

src/settings.c

GNOME Boxes needs access to input-sources so it can propagate the
host default sources to virtual machines that are automatically
created throughout our express-install technology.
See https://gitlab.gnome.org/GNOME/gnome-boxes/blob/master/src/unattended-installer.vala#L684
__________________
This is the backend counterpart of https://github.com/flatpak/xdg-desktop-portal/pull/367

settings: Expose "org.gnome.desktop.input-sources"

---

src/wallpaperpreview.c
src/wallpaperpreview.css
src/xdg-desktop-portal-gtk.gresource.xml

92beb8fe9941d91e1064b005c82dff29945650d5 is not related, but fixes a small regression introduced in https://github.com/flatpak/xdg-desktop-portal-gtk/commit/1d1302d70603710ddf1ec353a7ad9af80fdec057.

Wallpaper css fixes

---

src/gnomescreencast.c
src/screencast.c

With the new Mutter version and the inclusion of pipewire 0.3 support
into Mutter, the reported D-Bus version for the screencast API was
bumped to 3.
Update the supported version here as well. No code changes are necessary
to make it work with the version 3 of the API.

screencast: Bump supported Mutter version to 3

---

src/filechooser.c

The GtkFileChooserDialog preview-widget is visible by default. It
should only be visible when there's a preview to show.
Fixes #288

filechooser: Don't show an empty preview

---

src/appchooserdialog.c

Problem is the code reads off the end of the choices list when the number of choices is less than `INITIAL_LIST_SIZE - 1`.
Fixes #302

    appchooserdialog: avoid crash when there are few app options

---

src/gnomescreencast.c

Adds information about the shared content, using the newly added option from xdg-desktop-portal. See https://github.com/flatpak/xdg-desktop-portal/pull/492.
Patch from @jadahl.

Screencast: add information about source type to the response

---

src/background.c

Currently, they are two translatable strings that are almost the same, but the quotation mark.
So use the same string for both, with the quotation mark so that the name of the application is well separated from the surrounding message.
For reference, the original string is at line 215.

background: use the same message string

---

src/wallpaper.c
src/wallpaperdialog.c
src/wallpaperdialog.h
src/wallpaperdialog.ui
src/wallpaperpreview.c
src/wallpaperpreview.h
src/wallpaperpreview.ui

In GNOME 3.36 the lockscreen is now a blurried version of the
wallpaper. Although the gsetting for setting the lockscreen
background image will persist available, we should be consistent
with GNOME's UX decisions.
The frontend code should keep the "set-on" option, since other
desktop environments such as KDE might still have a separate
lockscreen image.
The "set-on" option will be simply ignored for the GTK backend.
See https://blogs.gnome.org/shell-dev/2020/02/18/login-and-unlock-in-gnome-shell-3-36/

wallpaper: Drop "lockscreen" option

---

src/print.c

When printing with an application under sandbox, the notification telling that it prints says "Document from %s" where %s is the app desktop file id (i.e. will print "Document from org.gnome.Evince" with evince).
This is not very clear what this name is in the notification, particularly with a third-party app (i.e. com.github.my_beautiful_github_name.app_name).
So this changes %s to the actual translated application name, looking in the corresponding desktop file entry.
--------------------------------------------------------------------------------------------------------------
I only have one doubt about my changes. in the docs for g_desktop_app_info_new, it says that `A desktop file id is the basename of the desktop file, including the .desktop extension` (talking about the first …

Use the application name in the print notification

---

src/wallpaperdialog.c

Commit 414adcac25458db38fb887d082cc52ab06ebf670
("wallpaper: Drop "lockscreen" option (#305)", 2020-05-29)
had removed the third (gboolean) param from
the 'wallpaper_preview_set_image' function, but one call
site still passed it, so the build failed with
CC       src/xdg_desktop_portal_gtk-wallpaperdialog.o
src/wallpaperdialog.c: In function ‘on_image_loaded_cb’:
src/wallpaperdialog.c:139:3: error: too many arguments to function ‘wallpaper_preview_set_image’
139 |   wallpaper_preview_set_image (self->desktop_preview,
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/wallpaperdialog.c:31:
src/wallpaperpreview.h:33:20: note: declared here
33 | void               wallpaper_preview_set_image (WallpaperPreview *self,
|                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
This PR fixes the …

Fix build after 414adcac25458db38fb887d082cc52ab06ebf670

---

src/gnomescreencast.c

The type for `source_type` value is [defined](https://github.com/flatpak/xdg-desktop-portal/blob/master/data/org.freedesktop.impl.portal.ScreenCast.xml#L150) as **u** and not **(u)**.

Screencast: use correct variant type

---

src/print.c

Add the same capabilities as in gtkprintoperation-unix.c.
Fixes GTK bug 1881 (inability to change scale).

Add some print capabilities to the print dialog.

---

src/gnomescreencast.c
src/remotedesktop.c
src/screencast.c

Version 4 added area recording, which we don't care about yet. No
existing API changed though, so mark version 4 as supported.

screencast: Drop all-or-nothing API version checks

---

src/screencastwidget.c

Some applications do not provide SVG icons, nor a range of icons,
only 64x64 or bigger. In these cases, even if the GtkImage is
created with the GTK_ICON_SIZE_DND (32px) hint passed, the window
icons would be bigger.
Fix that by forcing a 32px pixel size to the GtkImage.
Here's a picture of the bug:
and with this pull request:

Window sharing improvement

---

src/lockdown.c

This being bound to disable-sound-output was causing it to not update
the disable-microphone property in the lockdown dbus interface and
caused the corresponding gsettings setting to be reset every time
xdg-desktop-portal-gtk was started.

lockdown: Bind disable-microphone to the correct property

---

src/appchooserdialog.c

This happened trying to open a URI handled by a single application,
in this case a bjnb:// URL handled by the BlueJeans Flathub app.
```
XDP: Updating choices:
XDP: Updating choices: com.bluejeans.BlueJeans
(xdg-desktop-portal-gtk:691579): Gtk-CRITICAL **: 14:47:05.718: gtk_widget_get_visible: assertion 'GTK_IS_WIDGET (widget)' failed
```

appchooserdialog: Fix warning when there's no "more row"

---

src/filechooser.c

This prevents the new dialog from immediately losing focus when it opens on X11 systems.

filechooser: Avoid losing focus on X11

---

src/settings.c

See https://github.com/flatpak/xdg-desktop-portal/pull/633#issuecomment-922901502
The equivalent xdg-desktop-portal-gnome change:
https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/merge_requests/12

settings: Provide org.freedesktop.appearance.color-scheme key

---

src/fdonotification.c
src/notification.c

when dealing with vardicts `g_variant_lookup_value` expect the underlying type, or NULL, to return the variant. also, insert the parameter in a GVariantBuilder as expected in `org.freedesktop.Application.ActivateAction`.

notification: fix activation of action with target

---

configure.ac

These are not redundant with the GNOME version of these portals. They
are required for GTK apps running outside GNOME. It's a little sad that
we have portals in two different places, but I think that's just how it
needs to be.
Fixes #355

Enable settings and appchooser portals by default

---

src/fdonotification.c

g_variant_lookup_value expect the internal variant type, or NULL to return the variant itself.

notification: fix activation of default action with target

---

src/print.c

Note that earlier the fallback app_name may or may not have included
the .desktop extension as a suffix, depending on what was passed as
app_id to the function.  Now, it will always include the extension.
As a fallback, this shouldn't matter and being more predictable is
likely a good thing.
Fallout from 68c044c2c97261baa9b154ad29ab3ec826dd26b4

Don't leak app_name string if a desktop file or it's "Name" is absent

---

src/appchooser.c
src/screencastwidget.c
src/wallpaper.c
src/wallpaperdialog.c

These were originally detected only for `xdg-desktop-portal-gnome` because these GTK portals are disabled in Fedora land: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/merge_requests/46
This goes on top of https://github.com/flatpak/xdg-desktop-portal-gtk/pull/387

appchooser, wallpaper, wallpaperdialog: Fix a few memory errors and missing error handling pointed out by Coverity

---

src/email.c

Fixes https://github.com/flatpak/xdg-desktop-portal-gtk/issues/343

Fix crash when no addresses provided in ComposeEmail

---

src/notification.c

The GTK notifcation system (i.e. GNOME Shell) doesn't support notifcations without an ID and silently ignores them.
In this case, use the fdo notification system so these show.

notification: Use fdo notifictions for applications without IDs.

---

src/screenshot.c

Older forks of GNOME Shell (like MATE & Cinnamon) don't provide the
PickColor method, so return version 1 in this case. That way, clients
can check the version to know if they can call this or not.

screenshot: Check if PickColor is implemented

---

SECURITY.md

1.15.x doesn't yet exist, but when it does, it will be a development branch where security fixes might be accompanied by non-security changes that cause regressions.
I've assumed here that nobody is really maintaining 1.12.x, 1.10.x or 1.8.x. If there are CVEs, I'll have to backport fixes to 1.8.x if feasible (until Debian 11 EOL, expected in mid 2024) but I'm assuming there will not be an upstream release even if that happens.

Security support status: add 1.14.x, remove 1.8.x

---

src/dynamic-launcher.c
src/filechooser.c
src/print.c

The dynamic-launcher, filechooser, and print portals all use their handles after they've been freed by the call to *_handle_close(). Uh-oh.
See also: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/67

Don't use handles after freeing them

---

.github/workflows/test.yml

This PR bumps the version of `actions/checkout` and `actions/upload-artifact` from `v2` to `v3`. 
(Note: Upon, this PRs merge the Node 12 warning displayed under Annotations in actions will be fixed with the newer checkout version which uses Node 16). 
A test run of the changes can be found on my fork here https://github.com/kbdharun/xdg-desktop-portal-gtk/actions/runs/4638830439

test.yml: bump actions/checkout and actions/upload-artifact to v3 to fix Node warning

---

.github/workflows/test.yml

This PR bumps the `actions/checkout` version from v3 (Node 16) to v4 (Node 20) as Node 16 is reaching eol soon.
Ref. https://nodejs.org/en/blog/announcements/nodejs16-eol

CI: Bump actions/checkout to v4

---

src/fdonotification.c

This should fix a UAF when trying to scan across known `FdoNotification` nodes.
_May_ also fix: https://github.com/flatpak/xdg-desktop-portal-gtk/issues/422

fix: Don't add reused FdoNotification nodes to notifications slist

---

src/filechooser.c

`gtk_file_filter_new_from_gvariant ()` returns a `GtkFileFilter` which is a floating reference in GTK3. `gtk_file_chooser_set_filter ()` takes ownership of this floating reference. So, we take a ref to the filter to account for the autoptr cleanup.
Note that this happens only when we have a single filter ( with 1 or more rules ) set via `gtk_file_chooser_set_filter ()` in the app.

filechooser: Fix crash when opening a file chooser with single filter set

---

src/wallpaper.c

The Portal was setting the org.gnome.desktop.background picture-uri gsetting to a path, when applications expect an URI.
Fixes #374

wallpaper: Fix misuse of picture-uri gsetting

---

README.md
SECURITY.md
meson.build

The contributors to xdg-desktop-portal-gtk discussed the versioning policy, and decided to drop the even/odd split.
Update the documentation and security policies.

Update versioning policy

---

src/meson.build

The portals gated behind build options need a pre-processor symbol in order to be initialised.
The symbols were missing from the Meson build after the port from Autotools.
Fixes: #453

build: Add missing symbols

---

src/xdg-desktop-portal-gtk.c

With the https://flatpak.github.io/xdg-desktop-portal/ site revamp the URL to the DBus docs changed slightly.
Avoids a 404.

Fix link to DBus docs

---

src/settings.c

See https://github.com/flatpak/xdg-desktop-portal/pull/1175
Note: I still have questions how this work on a non GNOME system.... so it might not be relevant.
Mostly a cut and paste of https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/merge_requests/143

settings: Implement the contrast settings

---

src/settings.c

Mouse settings were moved from gnome-settings-daemon in 2015.

settings: Update mouse schema name

---

src/print.c

Respect the allowed output file formats set by apps.

print: Support "supported_output_file_formats" option

---

src/fdonotification.c

This PR addresses an issue with the urgency level mapping for notifications. The current implementation maps notifications with "high" urgency to "critical," which is not the standard practice. This change will adjust the mapping so that "high" urgency notifications are set to "normal."
See relevant issue https://github.com/flatpak/xdg-desktop-portal-gtk/issues/439

Handle "high" priority

---

data/xdg-desktop-portal-gtk.service.in

Otherwise portal unit might try to start before compositor exported `WAYLAND_DISPLAY` to activation environments.
[Reference](https://github.com/Vladimir-csp/uwsm/issues/37#issuecomment-2307818022)

Order startup after graphical-session.target

---

po/LINGUAS
po/ro.po

Added romanian translation as contributed by the members of Gnome Romanian Translation team.
Translation changes are tracked here: https://l10n.gnome.org/vertimus/xdg-desktop-portal-gtk/main/po/ro/

Added romanian translation

---

data/xdg-desktop-portal-gtk.service.in

Sorry, I got a bit confused in previous PR and removed this line. Indeed `PartOf=graphical-session.target` is a valid and useful directive, as it ensures the unit is properly brought down when graphical session is deactivating.
This will bring `-gtk` portal unit in line with others like `-wlr` or `-hyprland`.

Add PartOf

---

src/notification.c

This is needed as the impl interface is now marked with org.gtk.GDBus.C.UnixFD.

notification: Pass GUnixFDList on x-d-p >= 1.19.1
