flatpak/xdg-desktop-portal-gtk

- filechooser.c
We were still using cancel_label; so initialize it.
> Fix up an oversight in the last commit

- Makefile.am
- gtk.portal
- screenshot.c
- screenshotdialog.c
- screenshotdialog.ui
- xdg-desktop-portal-gtk.c
- xdg-desktop-portal-gtk.gresource.xml
This takes the 'shoot first, ask questions later' approach.
> Add a screenshot portal implementation

- screenshot.h
forgot to add this to the repository, it seems.
> Forgotten file

- Makefile.am
- appchooser.c
Fixes a warning and a build error
> Misc fixes

- Makefile.am
- gtk.portal
- notification.c
- notification.h
- org.gtk.Notifications.xml
- xdg-desktop-portal-gtk.c
This just forwards the calls to gnome-shell.
> Add a notification portal backend

- Makefile.am
- gtk.portal
- inhibit.c
- inhibit.h
- org.freedesktop.ScreenSaver.xml
- org.gnome.SessionManager.xml
- xdg-desktop-portal-gtk.c
This code talks to org.gnome.SessionManager to inhibit
various session state changes.
> Add an inhibit portal backend

- po/LINGUAS
- po/hu.po
Hi,
Here is the initial Hungarian translation.
> Added Hungarian translation

- configure.ac
- src/Makefile.am.inc
- src/externalwindow-wayland.c
- src/externalwindow-wayland.h
- src/externalwindow-x11.c
- src/externalwindow-x11.h
- src/externalwindow.c
- src/externalwindow.h
- src/filechooser.c
- src/utils.c
This needs gtk+ patches in https://bugzilla.gnome.org/show_bug.cgi?id=769788 and mutter patches in https://bugzilla.gnome.org/show_bug.cgi?id=769786 to function.
> Wayland support using xdg-foreign

- data/gtk.portal
- src/Makefile.am.inc
- src/email.c
- src/email.h
- src/xdg-desktop-portal-gtk.c
This is a very simple implmentation that just calls out
to evolution.
> Implement org.freedesktop.impl.portal.Email

- data/Makefile.am.inc
We need to dist the .desktop.in file and replace @libexecdir@ last.
> Fix desktop file generation

- src/appchooserdialog.c
- src/appchooserdialog.css
- src/appchooserdialog.ui
This is following the evolving app picker mockups.
> App picker: Add an empty state

- src/appchooser.c
- src/appchooserdialog.c
- src/appchooserdialog.css
- src/appchooserdialog.ui
- src/testappchooser.c
This requires the corresponding xdg-desktop-portal PR to be useful.
> Show uris as well in the app chooser

- src/print.c
Add a Preview button in the print dialog.
This relies on evince-previewer being installed.
> Add print preview

- po/LINGUAS
- po/zh_TW.po
I have just done Chinese (Taiwan) translation, please include it.
Thanks!
> Add Chinese (Taiwan) translation.

- src/externalwindow-wayland.c
- src/externalwindow-x11.c
- src/screenshot.c
- src/screenshotdialog.c
Some fixes to make the new flatpak demo app's screenshot test work.
> Screenshot fixes

- src/appchooserdialog.c
We don't want to make the dialog excessively wide because the location name is long.
This commit limits the location to an at-most 40 character suffix.
> app chooser dialog: Shorten locations

- src/email.c
Adds fallback if the default email handler is not Evolution or
Thunderbird that uses the GAppInfo's built-in support for mailto:
URIs. This adds support for e.g. Geary, both when installed locally and
also when it is itself installed via Flatpak.
* src/email.c (compose_mail): If app info command line neither contains
thunderbird or evolution, use a default mailto: URI handler.
> Add support for email clients in general using mailto: handler.

- data/Makefile.am.inc
- data/org.gnome.ScreenSaver.xml
- src/Makefile.am.inc
- src/inhibit.c
We implement this either with org.gnome.ScreenSaver,
or with org.freedeskop.ScreenSaver.
> inhibit: Implement screensaver monitoring

- po/zh_TW.po
I have updated Chinese (Taiwan) translation today.
> update to Chinese (Taiwan) translation

- po/it.po
Signed-off-by: Milo Casagrande <milo@milo.name>
> [l10n] Update Italian translation

- src/filechooser.c
Take the current_filter from the options dict and set it using
gtk_file_chooser_set_filter(). There are two possible uses:
(1) If filters were passed in the options dict, this selects one of them
to be the default filter. Previously, the first filter was always used
as default, which was wrong.
(2) If no filters were passed, this applies the filter unconditionally.
https://gitlab.gnome.org/GNOME/gtk/issues/1492
> filechooser: set file filter when requested

- src/inhibit.c
Add the session-state member to the StateChanged signal.
To track the session state, we register with org.gnome.SessionManager
and emit StateChanged signals in response to changes from the
session manager.
> inhibit: Implement session state tracking

- po/LINGUAS
- po/ru.po
> Add Russian translite

- src/screencast.c
- src/screencastwidget.c
> Minor fixes to screensharing

- po/it.po
Signed-off-by: Milo Casagrande <milo@milo.name>
> l10n: Update Italian translation

- src/filechooser.c
GTK implementation of new `SaveFiles` method using a
`GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER` file chooser.
See https://github.com/flatpak/xdg-desktop-portal/pull/368
> Implementation of org.freedesktop.portal.FileChooser::SaveFiles

- src/email.c
Testing confirms that both evolution and thunderbird
handle mailto urls fine, so just use that for everything.
> email: Simplify

- src/wallpaper.c
- src/wallpaperdialog.c
- src/wallpaperdialog.h
- src/wallpaperpreview.ui
> wallpaper: Cache remote images

- src/background.c
Listen to the gnome-shell signal of the same name,
compare the app state we got, and emit our own signal
if any apps changed to or from background state.
> background: Emit RunningApplicationsChanged

- src/settings.c
Starting with #241, animations are disabled in flatpak apps for users using
gnome-shell 3.34 or older.
> settings: Fallback to gsettings if the shell doesn't support enable-animations

- src/screenshot.c
We were not properly passing a canceled PickColor
call back to the frontend.
> screenshot: Fix handling of cancellation

- src/filechooser.c
Return the selected filter as 'current_filter', which is added to the FileChooser portal spec in [this pending pull request for xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal/pull/493).
This will allow making Gtk's 'gtk_file_chooser_get_filter' work for the portal native file chooser, s. https://gitlab.gnome.org/GNOME/gtk/-/issues/1820 for details
> filechooser: Return selected filter as 'current_filter'

- NEWS
- configure.ac
- data/Makefile.am.inc
- data/gtk.portal
- data/gtk.portal.in
- src/Makefile.am.inc
- src/xdg-desktop-portal-gtk.c
Make all the portals conditional that have buildtime or runtime GNOME dependencies.
> Gnome-free portals

- src/inhibit.c
GNOME Shell no longer constantly runs the org.gnome.ScreenSaver service
since gnome-shell!1520. Instead, it gets started on demand. This doesn't
work if we tell it not to autostart, causing the main codepath to always
fail. We wind up using the org.freedesktop.ScreenSaver fallback API
instead.
> inhibit: autostart org.gnome.ScreenSaver

- configure.ac
Those portal are now implemented in xdg-desktop-portal-gnome
> configure.ac: Disable most portals by default

- .github/workflows/test.yml
- data/gtk.portal.in
- src/Makefile.am.inc
- src/dynamic-launcher.c
- src/dynamic-launcher.h
- src/xdg-desktop-portal-gtk.c
This is based on the "Create Web Application" dialog from Epiphany,
adjusted to be more generalizable. The x-d-p side of this is here:
https://github.com/flatpak/xdg-desktop-portal/pull/696
> Implement dynamic launcher portal

- po/hi.po
Apparently the last translation is done by a non-native speaker. Though they did get some translations right, some of the translations were not apt. Here is an updated translation. In case, translations are not managed by pull requests in this project, enlighten me to follow the correct procedure.
> Correct and update Hindi (hi) translation

- po/POTFILES.in
Add missing src/dynamic-launcher.c  file to POTFILES.in
Fixes: #414
> Add dynamic-launcher.c to POTFILES.in

- po/LINGUAS
- po/be.po
Belarusian translation for xdg-desktop-portal-gtk
> Add Belarusian translation

- src/filechooser.c
<https://github.com/flatpak/xdg-desktop-portal/pull/874>
> filechooser: Support current_folder with OpenFile

- src/notification.c
To trigger it, send a notification.
> notification: fix a memory leak

- po/LINGUAS
- po/sl.po
Add the support for Slovenian (sl) language.
> Update LINGUAS - add Sloveninan (sl) language

- src/access.c
> access: Fix type of returned choices
